name: Backend CI Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Run Linter
        run: |
          cd code/backend
          uv run tox run -e lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Check formatting
        run: |
          cd code/backend
          uv run tox run -e format

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Run tests
        run: |
          cd code/backend
          uv run tox run -e test
        continue-on-error: true # TODO: remove when there are tests to run

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Run test coverage
        run: |
          cd code/backend
          uv run tox run -e coverage
        continue-on-error: true # TODO: remove when there are tests to run
  
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks (licensed action)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE_KEY }}

      # Upload to Code Scanning so findings show in Security tab
      - name: Upload SARIF to Code Scanning
        if: ${{ always() && hashFiles('gitleaks.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/event-manager-backend:latest

  security-deps:
    name: pip-audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pip-audit
      - name: Audit runtime requirements
        run: pip-audit -r code/backend/requirements.txt
      - name: Audit test requirements
        run: pip-audit -r code/backend/requirements-test.txt

  security-sast-semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Semgrep
        run: python -m pip install semgrep
      - name: Run Semgrep (OWASP + Python + Security Audit) # Run broad, maintained rulesets
        run: |
          semgrep ci \
            --config p/owasp-top-ten \
            --config p/python \
            --config p/security-audit