name: Backend CI Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Run Linter
        run: |
          cd code/backend
          uv run tox run -e lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Check formatting
        run: |
          cd code/backend
          uv run tox run -e format

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Run tests
        run: |
          cd code/backend
          uv run tox run -e test
        continue-on-error: true # TODO: remove when there are tests to run

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Run test coverage
        run: |
          cd code/backend
          uv run tox run -e coverage
        continue-on-error: true # TODO: remove when there are tests to run
# TODO: Add docker file image build and push to docker registry
